In [10]:
import pandas as pd 
import numpy as np

https://www.kaggle.com/datasets/dissfya/atp-tennis-2000-2023daily-pull

Este dataset, trae la informacion de los partidos de tenis de la ATP, en singles, de cada por año, desde  el 2000 a la actualidad. Analizando jugadores, torneos, superficies, y tasa de apuestas.

Variables.

Columnas	-->Explicación ( que es cada variable)
Tournament --> Nombre del torneo
Date    -->	   Fecha del partido
Series	-->    Tipo de torneo
Court   -->    Tipo de cancha (Aire libre o Cerrada)
Surface	-->    Tipo de superficie
Round	-->    Ronda del torneo
Best of -->    Mejor de 3/5 set 
Player_1-->    Jugador 1 (Nombre)
Player_2-->    Jugador 2 (Nombre)
Winner	-->    Ganador (Nombre)
Rank_1	-->    Ranking jugador 1
Rank_2	-->    Ranking jugador 2
Pts_1	-->    Puntos del jugador 1
Pts_2	-->    Puntos del jugador 2
Odd_1	-->    Cuota del jugador 1 (respecto a las apuestas)
Odd_2	-->    Cuota del jugador 2 (respecto a las apuestas)
Score	-->    Resultado del partido


Las variables de datos de tenis proporcionadas pueden utilizarse para analizar y predecir una variedad de aspectos del juego.

* Análisis de rendimiento.

* Comparar el rendimiento de jugadores individuales  en diferentes superficies.
* Identificar tendencias en el rendimiento de los jugadores a lo largo del tiempo.
* Identificar factores que contribuyen al rendimiento de los jugadores.
* Predicción de resultados

Las variables de datos de tenis se pueden utilizar para predecir los resultados de los partidos de tenis. 

Esto puede ayudar y beneficiar a:

*Ayudar a los apostadores a tomar decisiones de apuestas más informadas.
*Ayudar a los equipos de trabajo a planificar sus estrategias de juego.
*Ayudar a los organizadores de torneos a mejorar la planificación de los partidos.
*Ayudar a los entrenadores a evaluar el progreso de los jugadores.

*Identificar jugadores con potencial de crecimiento.
*Generar informes estadísticos sobre el juego del tenis.

In [11]:
3 leo el df
df=pd.read_csv("./atp_tennis.csv")
df

,Tournament,Date,Series,Court,Surface,Round,Best of,Player_1,Player_2,Winner,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2,Score
0,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Dosedel S.,Ljubicic I.,Dosedel S.,63,77,-1,-1,-1.00,-1.00,6-4 6-2
1,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Clement A.,Enqvist T.,Enqvist T.,56,5,-1,-1,-1.00,-1.00,3-6 3-6
2,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Escude N.,Baccanello P.,Escude N.,40,655,-1,-1,-1.00,-1.00,6-7 7-5 6-3
3,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Knippschild J.,Federer R.,Federer R.,87,65,-1,-1,-1.00,-1.00,1-6 4-6
4,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Fromberg R.,Woodbridge T.,Fromberg R.,81,198,-1,-1,-1.00,-1.00,7-6 5-7 6-4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61663,ASB Classic,2024-01-10,ATP250,Outdoor,Hard,Quarterfinals,3,Muller A.,Daniel T.,Daniel T.,79,74,711,739,1.91,1.91,4-6 7-6 3-6
61664,ASB Classic,2024-01-11,ATP250,Outdoor,Hard,Quarterfinals,3,Shelton B.,Carballes Baena R.,Shelton B.,16,67,2145,796,1.17,5.00,6-4 6-3
61665,ASB Classic,2024-01-12,ATP250,Outdoor,Hard,Semifinals,3,Shelton B.,Daniel T.,Daniel T.,16,74,2145,739,1.22,4.33,5-7 6-7
61666,ASB Classic,2024-01-12,ATP250,Outdoor,Hard,Semifinals,3,Tabilo A.,Fils A.,Tabilo A.,82,35,707,1208,4.00,1.25,6-2 7-5
61667,ASB Classic,2024-01-13,ATP250,Outdoor,Hard,The Final,3,Daniel T.,Tabilo A.,Tabilo A.,74,82,739,707,1.73,2.10,2-6 5-7

In [12]:
# 5 primeras filas
df.head()

,Tournament,Date,Series,Court,Surface,Round,Best of,Player_1,Player_2,Winner,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2,Score
0,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Dosedel S.,Ljubicic I.,Dosedel S.,63,77,-1,-1,-1.0,-1.0,6-4 6-2
1,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Clement A.,Enqvist T.,Enqvist T.,56,5,-1,-1,-1.0,-1.0,3-6 3-6
2,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Escude N.,Baccanello P.,Escude N.,40,655,-1,-1,-1.0,-1.0,6-7 7-5 6-3
3,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Knippschild J.,Federer R.,Federer R.,87,65,-1,-1,-1.0,-1.0,1-6 4-6
4,Australian Hardcourt Championships,2000-01-03,International,Outdoor,Hard,1st Round,3,Fromberg R.,Woodbridge T.,Fromberg R.,81,198,-1,-1,-1.0,-1.0,7-6 5-7 6-4

In [13]:
# 5 ultimas filas
df.tail()

,Tournament,Date,Series,Court,Surface,Round,Best of,Player_1,Player_2,Winner,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2,Score
61663,ASB Classic,2024-01-10,ATP250,Outdoor,Hard,Quarterfinals,3,Muller A.,Daniel T.,Daniel T.,79,74,711,739,1.91,1.91,4-6 7-6 3-6
61664,ASB Classic,2024-01-11,ATP250,Outdoor,Hard,Quarterfinals,3,Shelton B.,Carballes Baena R.,Shelton B.,16,67,2145,796,1.17,5.00,6-4 6-3
61665,ASB Classic,2024-01-12,ATP250,Outdoor,Hard,Semifinals,3,Shelton B.,Daniel T.,Daniel T.,16,74,2145,739,1.22,4.33,5-7 6-7
61666,ASB Classic,2024-01-12,ATP250,Outdoor,Hard,Semifinals,3,Tabilo A.,Fils A.,Tabilo A.,82,35,707,1208,4.00,1.25,6-2 7-5
61667,ASB Classic,2024-01-13,ATP250,Outdoor,Hard,The Final,3,Daniel T.,Tabilo A.,Tabilo A.,74,82,739,707,1.73,2.10,2-6 5-7

In [14]:
# descripcion estadistica de cada columna
df.describe()

,Best of,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2
count,61668.000000,61668.000000,61668.000000,61668.000000,61668.000000,61668.000000,61668.000000
mean,3.376986,76.028783,75.658948,1093.464017,1099.271389,2.399874,2.392321
std,0.782217,100.877203,101.533106,1707.213065,1730.729977,2.671125,2.624731
min,3.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,3.000000,25.000000,24.000000,-1.000000,-1.000000,1.330000,1.330000
50%,3.000000,54.000000,54.000000,671.000000,673.000000,1.727000,1.746042
75%,3.000000,92.000000,92.000000,1205.000000,1210.000000,2.750000,2.750000
max,5.000000,3390.000000,4915.000000,16950.000000,16950.000000,67.000000,51.000000

In [15]:
# tipos de datos de cada columna
df.dtypes

Tournament     object
Date           object
Series         object
Court          object
Surface        object
Round          object
Best of         int64
Player_1       object
Player_2       object
Winner         object
Rank_1          int64
Rank_2          int64
Pts_1           int64
Pts_2           int64
Odd_1         float64
Odd_2         float64
Score          object
dtype: object

In [16]:
# analisis de datos no nulos.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61668 entries, 0 to 61667
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Tournament  61668 non-null  object
 1   Date        61668 non-null  object
 2   Series      61668 non-null  object
 3   Court       61668 non-null  object
 4   Surface     61668 non-null  object
 5   Round       61668 non-null  object
 6   Best of     61668 non-null  int64
 7   Player_1    61668 non-null  object
 8   Player_2    61668 non-null  object
 9   Winner      61668 non-null  object
 10  Rank_1      61668 non-null  int64
 11  Rank_2      61668 non-null  int64
 12  Pts_1       61668 non-null  int64
 13  Pts_2       61668 non-null  int64
 14  Odd_1       61668 non-null  float64
 15  Odd_2       61668 non-null  float64
 16  Score       61668 non-null  object
dtypes: float64(2), int64(5), object(10)
memory usage: 8.0+ MB